# fly.toml app configuration file generated for n8n-app-dry-frog-9139 on 2025-07-24T17:40:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "n8n-app"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  GENERIC_TIMEZONE = "Asia/Tokyo"
  TZ = "Asia/Tokyo"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "changeme"
  N8N_HOST = "0.0.0.0"
  PORT = "8080"
  N8N_PORT = "8080"
  WEBHOOK_TUNNEL_URL = "https://n8n-app.fly.dev"
  NODE_OPTIONS = "--max-old-space-size=4096"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  
  [http_service.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[[mounts]]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[deploy]
  strategy = "immediate"

[processes]
  app = "n8n"
