app = "n8n-app"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  GENERIC_TIMEZONE = "Asia/Tokyo"
  TZ = "Asia/Tokyo"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "changeme"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  WEBHOOK_TUNNEL_URL = "https://n8n-app.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

[[mounts]]
  source = "n8n_data"
  destination = "/home/node/.n8n" 